
# web config DEV
server.port=5000
server.ip=127.0.0.1


# AI ????
# ??????????????
ai.model.type=deepseek
# ????????????????????????????????
ai.model.name=deepseek-chat
ai.model.apikey=SK2328493489afiafaffjdj
ai.model.url=https://api.deepseek.com

#????


